import React from 'react';
import { ShieldCheck, Lock, HeartHandshake, Compass } from 'lucide-react';

export const EthicsSection: React.FC = () => {
  return (
    <section id="ethics" className="py-24 bg-[#F8FAFC] text-[#0F172A] border-b border-[#E2E8F0]">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 space-y-16">
        
        {/* Header */}
        <div className="max-w-3xl space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#FFFFFF] border border-[#CBD5E1] text-[#0F172A] text-xs font-mono font-bold uppercase tracking-wider">
            <span>GOVERNANCE & INTEGRITY</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-black tracking-tight text-[#0F172A]">
            Product, ethics, and user sovereignty stay close.
          </h2>
          <p className="text-base text-[#475569] leading-relaxed">
            Astrology practiced responsibly is an instrument of psychological self-inquiry and conscious life design—never an apparatus of fear, dependence, or fatalism.
          </p>
        </div>

        {/* 4 Core Blocks */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          
          <div className="p-8 bg-[#FFFFFF] border border-[#E2E8F0] space-y-4 shadow-sm">
            <div className="w-10 h-10 bg-[#0F172A] text-white flex items-center justify-center font-bold">
              <Compass className="w-5 h-5 text-[#FF552E]" />
            </div>
            <h3 className="font-bold text-lg text-[#0F172A]">Sovereignty of Will</h3>
            <p className="text-xs text-[#475569] leading-relaxed">
              Planetary configurations describe energetic inclinations and temporal seasons. Conscious human decisions forever preserve ultimate sovereignty over outcomes.
            </p>
          </div>

          <div className="p-8 bg-[#FFFFFF] border border-[#E2E8F0] space-y-4 shadow-sm">
            <div className="w-10 h-10 bg-[#0F172A] text-white flex items-center justify-center font-bold">
              <ShieldCheck className="w-5 h-5 text-[#FF552E]" />
            </div>
            <h3 className="font-bold text-lg text-[#0F172A]">Absolute Non-Fatalism</h3>
            <p className="text-xs text-[#475569] leading-relaxed">
              We strictly prohibit deterministic forecasting regarding mortality or catastrophic doom. Astra provides grounded coaching, never existential dread.
            </p>
          </div>

          <div className="p-8 bg-[#FFFFFF] border border-[#E2E8F0] space-y-4 shadow-sm">
            <div className="w-10 h-10 bg-[#0F172A] text-white flex items-center justify-center font-bold">
              <HeartHandshake className="w-5 h-5 text-[#FF552E]" />
            </div>
            <h3 className="font-bold text-lg text-[#0F172A]">Jungian Integration</h3>
            <p className="text-xs text-[#475569] leading-relaxed">
              Anchored in Carl Jung’s archetypes, planetary markers serve as mirrors to the shadow, the anima/animus, and the lifelong journey toward self-actualization.
            </p>
          </div>

          <div className="p-8 bg-[#FFFFFF] border border-[#E2E8F0] space-y-4 shadow-sm">
            <div className="w-10 h-10 bg-[#0F172A] text-white flex items-center justify-center font-bold">
              <Lock className="w-5 h-5 text-[#FF552E]" />
            </div>
            <h3 className="font-bold text-lg text-[#0F172A]">Data Sovereignty</h3>
            <p className="text-xs text-[#475569] leading-relaxed">
              Exact natal coordinates, times, and consultations are treated as private confidences. We do not sell user data or train external commercial models on private chats.
            </p>
          </div>

        </div>

        {/* Notice Banner */}
        <div className="p-6 bg-[#0F172A] text-white space-y-2 border-l-4 border-[#FF552E]">
          <div className="font-mono text-xs uppercase tracking-wider text-[#FF552E] font-bold">
            Ethical Scope Limitation
          </div>
          <p className="text-xs text-[#CBD5E1] leading-relaxed">
            Astrological interpretations generated by Astra are intended strictly for philosophical introspection, archetypal self-reflection, and personal life coaching. Astra does not provide medical diagnoses, psychiatric psychotherapy, legal counsel, or financial investment underwriting.
          </p>
        </div>

      </div>
    </section>
  );
};
